# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Endpoint Security
email: info@endpoint-sec.com
description: We deliver the ultimate air-gap security for remote endpoints by ensuring data is only decrypted at the user’s eye level.
baseurl: ""
domain: "endpoint-sec.com"
url: "https://www.endpoint-sec.com/"

remote_theme: just-the-docs/just-the-docs@v0.10.1
logo: assets/logo.png
nav_enabled: false
search_enabled: false
heading_anchors: false

color_scheme: endpoint

callouts_level: quiet
callouts:
  highlight:
    color: endpoint

ga_tracking: G-X4W72FT9JQ
ga_tracking_anonymize_ip: true
